jalabel_site/jalabel_app/urls.py
from django.urls import path

from . import views

app_name = 'jalabel_app'
urlpatterns = [
    path('', views.index, name='index'),
    path('capture/add/', views.CaptureCreate.as_view(), name='capture-create'),
    path('capture/<int:pk>/', views.CaptureUpdate.as_view(), name='capture-update'),
    path('capture/<int:pk>/delete/', views.CaptureDelete.as_view(), name='capture-delete'),
    path('dashboard/', views.Dashboard.as_view(), name='dashboard')
]

jalabel_site/jalabel_site/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

urlpatterns = [
    path('', include('jalabel_app.urls')),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)\
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jalabel_site/jalabel_app/models.py
from django.db import models
from sorl import thumbnail
from django.urls import reverse


class FixtureData(models.Model):
    lot_number = models.CharField(max_length=20)
    image_data = thumbnail.ImageField(upload_to='fixture/', blank=True)
    message = models.CharField(max_length=20, default='unknown')
    uploaded_date = models.DateTimeField(unique=True)
    last_modified = models.DateTimeField(auto_now=True)
    rle_csv = models.ImageField(upload_to='fixture_rle/', blank=True)

    def get_absolute_url(self):
        return '../add/'

jalabel_site/jalabel_app/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from .models import FixtureData


class FixtureDataForm(forms.ModelForm):
    class Meta:
        model = FixtureData
        fields = ('uploaded_date', 'lot_number', 'message', 'image_data', 'rle_csv')
        widgets = {
            'message': forms.HiddenInput(),
            'rle_csv': forms.HiddenInput(),
            'image_data': forms.ClearableFileInput(attrs={'multiple': True})
        }

    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.form_id = 'uploadForm'
        self.helper.form_method = 'post'

        super(FixtureDataForm, self).__init__(*args, **kwargs)


class SearchForm(forms.Form):
    uploaded_date_from = forms.DateTimeField(required=False)
    uploaded_date_to = forms.DateTimeField(required=False)
    lot_number = forms.CharField(max_length=20, required=False)
    message = forms.CharField(max_length=20, required=False)
    option = forms.CharField(max_length=20)

    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.form_id = 'searchForm'
        self.helper.form_method = 'post'

        super(SearchForm, self).__init__(*args, **kwargs)

jalabel_site/jalabel_app/views.py
from pathlib import Path

from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView
from django.views.generic.edit import FormView, CreateView, UpdateView, DeleteView
from django.http import JsonResponse
from django.shortcuts import render
from django.conf import settings

from .models import FixtureData
from .forms import SearchForm
from . import fixture_ai
import datetime

from crispy_forms.helper import FormHelper

fdo = FixtureData.objects


def index(request):
    fixtures = {'fixtures': [fd for fd in fdo.order_by('uploaded_date').values()]}
    return render(request, 'jalabel_app/index.html', fixtures)


class CaptureCreate(CreateView):
    model = FixtureData
    fields = ['uploaded_date', 'lot_number', 'image_data']

    fai = fixture_ai.FixtureAI()

    def form_invalid(self, form, *args, **kwargs):
        response = super().form_valid(form)
        return response

    def form_valid(self, form, *args, **kwargs):
        response = super().form_valid(form)

        fixture_data_object = form.save()
        prediction = self.fai.predict(self.request.FILES['image_data'])
        rle_path = 'fixture_rle/' + Path(fixture_data_object.image_data.name).name
        prediction.save(settings.MEDIA_ROOT + rle_path)
        fixture_data_object.rle_csv.name = rle_path
        fixture_data_object.save()
        return JsonResponse({'id': fixture_data_object.id})

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.helper = FormHelper()
        form.helper.form_id = 'uploadForm'
        form.helper.form_method = 'post'
        return form


class CaptureUpdate(UpdateView):
    model = FixtureData
    fields = ['uploaded_date', 'lot_number', 'message', 'image_data', 'rle_csv']
    template_name_suffix = '_update_form'

    def form_valid(self, form):
        response = super().form_valid(form)
        fixture_data_object = form.save()
        fixture_data_object.save()
        return response

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.helper = FormHelper()
        form.helper.form_id = 'uploadForm'
        form.helper.form_method = 'post'
        return form


class CaptureDelete(DeleteView):
    model = FixtureData
    success_url = reverse_lazy('jalabel_app:capture-create')


class Dashboard(FormView):
    template_name = 'jalabel_app/dashboard.html'
    form_class = SearchForm
    success_url = '/dashboard/'

    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        number_of_objects = len(FixtureData.objects.all())

        context = {'form': self.form_class,
                   'dates': self.get_dates()}
        if number_of_objects > 48:
            context.update({'fixtures': fdo.order_by('-uploaded_date')[0:48]})
        else:
            context.update({'fixtures': fdo.order_by('-uploaded_date')})

        return context

    def form_invalid(self, form):
        response = super().form_invalid(form)
        if self.request.is_ajax():
            print('it`s ajax but invalid')
            print(form.errors)
            return JsonResponse(form.errors, status=400)
        else:
            print('it isn`t ajax and invalid')
            return response

    def form_valid(self, form):
        response = super().form_valid(form)
        if self.request.is_ajax():
            print('it`s ajax and valid')
            return response
        else:
            print('it isn`t ajax but valid ' + form.cleaned_data['option'])
            if form.cleaned_data['option'] == 'day':
                context = {'form': self.form_class,
                           'dates': self.get_dates(),
                           'fixtures': fdo.filter(
                               uploaded_date__contains=form.cleaned_data['uploaded_date_from'].date())}
                return render(self.request, 'jalabel_app/dashboard.html', context)
            elif form.cleaned_data['option'] == 'lot number':
                print(form.cleaned_data['lot_number'])
                context = {'form': self.form_class,
                           'dates': self.get_dates(),
                           'fixtures': fdo.filter(
                               lot_number__contains=form.cleaned_data['lot_number'])}
                return render(self.request, 'jalabel_app/dashboard.html', context)
            else:
                pass
            return response

    def get_dates(self):
        if len(FixtureData.objects.all()) > 0:
            first_day = fdo.order_by('uploaded_date')[0].uploaded_date.date()
            last_day = fdo.order_by('-uploaded_date')[0].uploaded_date.date()
            dates = []
            for x in range((last_day-first_day).days + 1):
                date = first_day + datetime.timedelta(days=x)
                length = len(fdo.filter(uploaded_date__contains=date))
                if length > 0:
                    dates.append({'date': date, 'number_of_data': length})
            return dates

jalabel_site/jalabel_app/templates/jalabel_app/dashboard.html
<html lang="en">

{% load static %}
{% load thumbnail %}
{% load crispy_forms_tags %}

<head>
    <title>Dashboard</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="A front-end template that helps you build fast, modern mobile web apps.">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:regular,bold,italic,thin,light,bolditalic,black,medium&amp;lang=en">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.cyan-light_blue.min.css">
    <link rel="shortcut icon" type="image/png" href='{% static "favicon/favicon.ico" %}'>
    <link rel="stylesheet" type="text/css" href='{% static "jalabel_app/dashboard.css" %}'>
    <style>
        #view-source {
            position: fixed;
            display: block;
            right: 0;
            bottom: 0;
            margin-right: 40px;
            margin-bottom: 40px;
            z-index: 900;
        }
    </style>
</head>

<body>
<div class="demo-layout mdl-layout mdl-js-layout mdl-layout--fixed-drawer mdl-layout--fixed-header">
    <header class="demo-header mdl-layout__header mdl-color--grey-100 mdl-color-text--grey-600">
        <div class="mdl-layout__header-row">
            <span class="mdl-layout-title">Home</span>
            <div class="mdl-layout-spacer"></div>
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--expandable">
                <label class="mdl-button mdl-js-button mdl-button--icon" for="search">
                    <i class="material-icons">search</i>
                </label>
                <div class="mdl-textfield__expandable-holder">
                    <input class="mdl-textfield__input" type="text" id="search">
                    <label class="mdl-textfield__label" for="search">Enter your query...</label>
                </div>
            </div>
            <button class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon" id="hdrbtn">
                <i class="material-icons">more_vert</i>
            </button>
            <ul class="mdl-menu mdl-js-menu mdl-js-ripple-effect mdl-menu--bottom-right" for="hdrbtn">
                <li class="mdl-menu__item">About</li>
                <li class="mdl-menu__item">Contact</li>
                <li class="mdl-menu__item">Legal information</li>
            </ul>
        </div>
    </header>
    <div class="demo-drawer mdl-layout__drawer mdl-color--blue-grey-900 mdl-color-text--blue-grey-50">
        <header class="demo-drawer-header">
            <img src='{% static "image/user.jpg" %}' class="demo-avatar">
            <div class="demo-avatar-dropdown">
                <span>hello@example.com</span>
                <div class="mdl-layout-spacer"></div>
                <button id="accbtn" class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon">
                    <i class="material-icons" role="presentation">arrow_drop_down</i>
                    <span class="visuallyhidden">Accounts</span>
                </button>
                <ul class="mdl-menu mdl-menu--bottom-right mdl-js-menu mdl-js-ripple-effect" for="accbtn">
                    <li class="mdl-menu__item">hello@example.com</li>
                    <li class="mdl-menu__item">info@example.com</li>
                    <li class="mdl-menu__item"><i class="material-icons">add</i>Add another account...</li>
                </ul>
            </div>
        </header>
        <nav class="demo-navigation mdl-navigation mdl-color--blue-grey-800">
            <a class="mdl-navigation__link" href="/dashboard/">
                <i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">
                    home
                </i>
                Home
            </a>
            <a class="mdl-navigation__link" href="/capture/add/">
                <i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">
                    camera_alt
                </i>
                Capture
            </a>
            <a class="mdl-navigation__link" href="">
                <i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">
                    delete
                </i>
                Trash
            </a>
            <a class="mdl-navigation__link" href="">
                <i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">
                    report
                </i>
                Spam
            </a>
            <a class="mdl-navigation__link" href="">
                <i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">
                    forum
                </i>
                Forums
            </a>
            <a class="mdl-navigation__link" href="">
                <i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">
                    flag
                </i>
                Updates
            </a>
            <a class="mdl-navigation__link" href="">
                <i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">
                    local_offer
                </i>
                Promos
            </a>
            <a class="mdl-navigation__link" href="">
                <i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">
                    shopping_cart
                </i>
                Purchases
            </a>
            <a class="mdl-navigation__link" href="">
                <i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">
                    people
                </i>
                Social
            </a>
            <div class="mdl-layout-spacer"></div>
            <a class="mdl-navigation__link" href=""><i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">help_outline</i><span class="visuallyhidden">Help</span></a>
        </nav>
    </div>
    <main class="mdl-layout__content mdl-color--grey-100">
        <div class="mdl-grid date">
            {% for d in dates %}
            <div class="mdl-cell mdl-cell--2-col">
                {{ d.date|date:'Y-m-d' }}({{ d.number_of_data }})
            </div>
            {% endfor %}
        </div>
        <div class="mdl-grid data">
            {% load cache %}
            {% cache 1 contents %}
            {% for fixture in fixtures %}
            <div class="mdl-cell mdl-cell--2-col">
                <div class="image_div">
                    {% thumbnail fixture.image_data "150x100" as im %}
                    <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
                    {% endthumbnail %}
                </div>
                <div class="fixture-id">{{ fixture.id}}</div>
                <div class="fixture-uploaded-date">{{ fixture.uploaded_date|date:'Y-m-d H:i:s.u'}}</div>
                <div class="fixture-lot-number">{{ fixture.lot_number }}</div>
                <div class="fixture-message" hidden>{{ fixture.message }}</div>
            </div>
            {% endfor %}
            {% endcache %}
        </div>
        <div hidden class="form-wrapper">
            {% crispy form %}
        </div>
    </main>
</div>
<script rel="javascript" type="text/javascript" src='{% static "jalabel_app/js/jquery-3.4.1.min.js" %}'></script>
<script src="https://code.getmdl.io/1.3.0/material.min.js"></script>
<script>
    let data = document.getElementsByClassName('mdl-grid data')[0].children;
    for(let elem of data){
        elem.addEventListener('click', function(){
            location.href = window.origin + '/capture/' + elem.children[1].innerText + '/';
        });

        switch(elem.children[4].innerText){
            case 'perfect':
                elem.style.backgroundColor = 'rgba(0,255,0,0.1)';
                break;
            case 'defect':
                elem.style.backgroundColor = 'rgba(255,255,0,0.1)';
                break;
            case 'later':
                elem.style.backgroundColor = 'rgba(255,0,0,1)';
                break;
            case 'unknown':
                elem.style.backgroundColor = 'rgba(0,255,255,1)';
        }
    }

    let date = document.getElementsByClassName('mdl-grid date')[0].children;
    for(let elem of date){
        elem.addEventListener('click', function(){
            $('#id_option').val('day');
            $('#id_uploaded_date_from').val(this.innerText.split('(')[0]);
            $('#searchForm').submit();
        });
    }

    let search = document.getElementById('search');
    search.addEventListener('keydown', function(event) {
        const keyName = event.key;
        switch(keyName){
            case 'Enter':
                $('#id_option').val('lot number');
                $('#id_lot_number').val(search.value);
                $('#searchForm').submit();
                break;
        }
    }); 
</script>
</body>
</html>

jalabel_site/jalabel_app/templates/jalabel_app/fixturedata_confirm_delete.html
<!DOCTYPE html>

{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Delete</title>
    <link rel="shortcut icon" type="image/png" href='{% static "favicon/favicon.ico" %}'>
</head>
<body>
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>
</body>
<script>
    const csrftoken = $("[name=csrfmiddlewaretoken]").val();

    window.onload = function(){
        location.href = window.origin + '/capture/add/'
    }
</script>
</html>

jalabel_site/jalabel_app/templates/jalabel_app/fixturedata_form.html
<!DOCTYPE html>

{% load static %}
{% load crispy_forms_tags %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Capture</title>
    <link rel="shortcut icon" type="image/png" href='{% static "favicon/favicon.ico" %}'>
    <link rel="stylesheet" type="text/css" href='{% static "jalabel_app/capture.css" %}'>
</head>
<body>
<div class="container">
    <div class="image_div">
        <video id="player" autoplay></video>
        <canvas id="image_canvas"></canvas>
    </div>
    <div class="form-wrapper">
        {% crispy form %}
    </div>
    <div class="bottom-button-group" id="capture-buttons">
        <button id="dashboard" class="bottom-button">Dashboard(Esc)</button>
        <button id="capture" class="bottom-button">Capture(S, Space)</button>
    </div>
</div>
</body>
<script rel="javascript" type="text/javascript" src='{% static "jalabel_app/js/jquery-3.4.1.min.js" %}'></script>
<script>
    const csrftoken = $("[name=csrfmiddlewaretoken]").val();

    const capture_buttons = document.getElementById('capture-buttons');
    const captureButton = document.getElementById('capture');
    const dashboardButton = document.getElementById('dashboard');

    const player = document.getElementById('player');

    const width = 1920;
    const height = 1080;

    const image_canvas = document.getElementById('image_canvas');
    const image_context = image_canvas.getContext('2d');

    image_canvas.width = width;
    image_canvas.height = height;

    let image = new Image();

    image.onload = function(){
        image_context.image = image;
        image_context.clearRect(0, 0, image_context.width, image_context.height);
        image_context.drawImage(this, 0, 0);
        image_canvas.setAttribute('tabindex','0');
        image_canvas.focus();
    };

    let clock_id;

    function currentDateTime(){
        let today = new Date();
        let time_string = today.getFullYear() + '-' +
            (today.getMonth()+1).toString().padStart(2, '0') + '-' +
            today.getDate().toString().padStart(2, '0') + ' ' +
            today.getHours().toString().padStart(2, '0') + ':' +
            today.getMinutes().toString().padStart(2, '0') + ':' +
            today.getSeconds().toString().padStart(2, '0') + '.' +
            today.getMilliseconds().toString().padStart(3, '0') + '000';

        $('#id_uploaded_date').val(time_string)
    }

    window.onload = function(){
        try{
            navigator.getUserMedia({
                //video: true,
                video: {width: {exact: width}, height: {exact: height}}
            }, function(stream){
                player.srcObject = stream;
            }, function(error){
            });
        } catch(err) {
        }
        clock_id = setInterval(currentDateTime, 1);

        let lot_number = getCookie('lot_number')
        if(lot_number != undefined){
            $('#id_lot_number').val(lot_number)
        }
    };

    let getCookie = function(cname){
        for(cookie of document.cookie.split('; ')){
            let cs = cookie.split('=')
            if(cs[0] == cname){
                return cs[1]
            }
        }

        return undefined
    }

    $("#id_lot_number").change(function(e){
        document.cookie = 'lot_number=' + $("#id_lot_number").val()
    });

    $("#id_image_data").change(function(e) {
        let reader = new FileReader();
        reader.onload = function(){
            image.src = reader.result
        };
        reader.readAsDataURL(e.target.files[0]);

        image_canvas.style.visibility = "visible";
        capture_buttons.style.visibility = "visible"
    });

     let capture = function() {
        clearInterval(clock_id);

        if (player.srcObject != null) {
            image_context.drawImage(player, 0, 0, image_canvas.width, image_canvas.height);
        }
        image_canvas.toBlob(function(blob) {
            let formData = new FormData(document.getElementById('uploadForm'));
            formData.set('message', 'unknown');
            formData.set('image_data', blob, ($('#id_uploaded_date').val() + '_' + $('#id_lot_number').val()+'.png'));
            $.ajax({
                beforeSend: function (xhr) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                    // xhr.setRequestHeader('X-Requested-With', 'XMLHttpRequest');
                },
                url: window.location.origin + '/capture/add/',
                data: formData,
                cache: false,
                contentType: false,
                processData: false,
                method: 'post',
                type: 'post',
                success: function(data) {
                    console.log(data);
                    location.href = window.origin + '/capture/' + data['id'] + '/'
                },
                error: function (jqXHR, textStatus, errorThrown) {
                    alert(jqXHR.responseText);
                }
            });
        });
    };

    let dashboard = function(){
        window.location.href = window.origin + '/dashboard/';
        return false;
    };

    captureButton.addEventListener('click', capture);
    dashboardButton.addEventListener('click', dashboard);
    document.addEventListener('keydown', function(event) {
        const keyName = event.key;
        if(document.activeElement.id != 'id_lot_number'){
            console.log(keyName);
            switch (keyName) {
                case 'Escape':
                    setTimeout(dashboard, 10);
                    break;
                case 's':
                case 'S':
                case 'b':
                case 'B':
                case ' ':
                    capture();
                    break;
            }
        }
    });
</script>
</html>

jalabel_site/jalabel_app/templates/jalabel_app/index.html
<!DOCTYPE html>

{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
    <link rel="shortcut icon" type="image/png" href='{% static "favicon/favicon.ico" %}'>
</head>
<style>
    body {
        margin-top: 2%;
        margin-left: 2%;
        width:800px;
    }
</style>
<body>
<h1>Fixture Inspector</h1>
GitLab URL : <a href=https://gitlab.cybermed.co.kr/jaewonac/fixtureinspector>gitlab.cybermed.co.kr/jaewonac/fixtureinspector</a>
<br>문제점 및 건의사항 : <a href=https://gitlab.cybermed.co.kr/jaewonac/fixtureinspector/-/issues>gitlab.cybermed.co.kr/jaewonac/fixtureinspector/-/issues</a>
<h1>Description.</h1>
<h2 id='dashboard'><a href='/dashboard/'>Dashboard</a></h2>
URL : http://origin-url/dashboard/
<br>현재 서버에 저장되어 있는 이미지들을 보여줍니다. 각 이미지들은
<li>양품 : 옅은 녹색</li>
<li>불량 : 옅은 적록색</li>
<li>연기 : 진한 적색</li>
<li>미정 : 진한 청록색</li>
으로 표시됩니다. 이미지를 클릭하면 상세사항을 확인할 수 있습니다.

우측 상단의 검색 버튼을 누르면, Lot number를 입력할 수 있으며, 입력 후 Enter를 치면 검색결과가 뜹니다.

<h2 id='capture'><a href='/capture/add/'>Capture</a></h2>
URL : http://origin-url/capture/
<br>카메라가 연결되어 있으면 영상을 캡쳐하며, 좌측 상단의 파일 선택을 통해 컴퓨터에 있는 파일을 업로드 할 수 있습니다.
Capture 버튼을 누르면 이미지가 서버로 업로드되며 약 1~2초 후에 AI를 통해 검출된 불량 부분을 보여줍니다.

<h2>불량 표시 및 저장</h2>
Dashboard에서 이미지 클릭 후 또는 Capture에서 Capture 후에 불량 부분을 확인 및 수정할 수 있으며,
 이미지를 '불량', '양품' '나중'으로 분류하여 저장할 수 있습니다.
<h3>불량 확인 및 수정</h3>
<li>Shift + 마우스 휠 : 영상 확대 축소</li>
<li>Shift + 좌 클릭 & 드래그 : 영상 이동</li>
<li>Ctrl + 좌 클릭 : 다각형으로 불량 부분 표시 시작</li>
<li>Ctrl + 우 클릭 : 다각형 완성</li>
<li>Alt + 좌 클릭 : 지우개(커서가 사각형으로 변하며 사각형 내부의 불량을 삭제)</li>
<li>Alt + 마우스 휠 : 지우개 크기 변경</li>

<h3>분류</h3>
<li>Delete(A) : 업로드된 이미지를 삭제</li>
<li>Perfect(S, Space) : 표시된 불량은 무시하고, 양품으로 분류합니다. Dashboard에서 옅은 녹색으로 표시됩니다.</li>
<li>Defect(D) : 표시된 불량대로 불량품으로 분류합니다. Dashboard에서 옅은 적색으로 표시됩니다.</li>
<li>Later(F) : 나중으로 미룹니다. Dashboard에서 청록색으로 표시됩니다.</li>

</body>
</html>